# Generated by Django 5.0.6 on 2024-05-30 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fake_steam_api', '0002_alter_item_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Accepted'), ('R', 'Rejected'), ('C', 'Canceled')], default='P', max_length=1),
        ),
    ]
